# Use this as docker-compose.override.yml if you use Mac
version: '3.7'

services:
  fpm:
    volumes:
      #- .:/app #uses docker native FS bridge
      - nfsmount:/app
      - ~/.composer/cache:/.composer/cache
      - ./containers/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    user: "501:20"
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

#May cause trouble in newer MacOS versions, if so use native FS bridge
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3